//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataDetail
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public int P0 { get; set; }
        public int p1 { get; set; }
        public int p2 { get; set; }
        public int p3 { get; set; }
        public int p4 { get; set; }
        public int p5 { get; set; }
        public int p6 { get; set; }
        public int p7 { get; set; }
        public int p8 { get; set; }
        public int p9 { get; set; }
        public int p10 { get; set; }
        public int p11 { get; set; }
        public int p12 { get; set; }
        public int p13 { get; set; }
        public int p14 { get; set; }
        public int p15 { get; set; }
        public int p16 { get; set; }
        public int p17 { get; set; }
        public int p18 { get; set; }
        public int p19 { get; set; }
        public int p20 { get; set; }
        public int p21 { get; set; }
        public int p22 { get; set; }
        public Nullable<System.DateTime> Datewrite { get; set; }
    }
}
